### ISSUE TITLE
Error on 'templates' when running gulp

### ISSUE THREAD

**Issue by iansoper** [airtonix/assemble-gulp-patternlab#1]
Get the following error when running gulp task:
```
'templates' errored after 4.99 ms
TypeError: undefined is not a function
```
Full log below:
```
[15:38:38] Requiring external module coffee-script/register
[15:38:43] Using gulpfile ~/code/assemble-gulp-patternlab/gulpfile.coffee
[15:38:43] Starting 'clean:scripts'...
[15:38:43] Finished 'clean:scripts' after 13 ms
[15:38:43] Starting 'clean:styles'...
[15:38:43] Finished 'clean:styles' after 3.32 ms
[15:38:43] Starting 'clean:images'...
[15:38:43] Finished 'clean:images' after 1.91 ms
[15:38:43] Starting 'clean:fonts'...
[15:38:43] Finished 'clean:fonts' after 1.98 ms
[15:38:43] Starting 'clean:templates'...
[15:38:43] Finished 'clean:templates' after 798 μs
[15:38:43] Starting 'clean'...
[15:38:43] Finished 'clean' after 11 μs
[15:38:43] Starting 'styles'...
[15:38:43] Finished 'styles' after 3.19 ms
[15:38:43] Starting 'scripts'...
[15:38:43] Finished 'scripts' after 1.71 ms
[15:38:43] Starting 'images'...
[15:38:43] Finished 'images' after 2.3 ms
[15:38:43] Starting 'fonts'...
[15:38:43] Finished 'fonts' after 1.59 ms
[15:38:43] Starting 'data'...
[15:38:43] Finished 'data' after 704 μs
[15:38:43] Starting 'templates'...
[15:38:43] 'templates' errored after 4.99 ms
[15:38:43] TypeError: undefined is not a function
  at Object.posix.isAbsolute (path.js:479:15)
  at posix.normalize (path.js:461:26)
  at Array.map (native)
  at [object Object].Loader.extend.init (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/template-nunjucks/node_modules/nunjucks/src/node-loaders.js:20:44)
  at new new_cls (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/template-nunjucks/node_modules/nunjucks/src/object.js:44:28)
  at Function.engine.configure (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/template-nunjucks/index.js:104:45)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:149:11)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:184:2)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:131:2)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:124:2)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:140:2)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:116:2)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:60:3)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:97:2)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:91:2)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:85:2)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:79:2)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at Gulp.<anonymous> (/Users/iansoper/code/assemble-gulp-patternlab/gulpfile.coffee:72:2)
  at module.exports (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/Users/iansoper/code/assemble-gulp-patternlab/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
  at /Users/iansoper/code/assemble-gulp-patternlab/node_modules/assemble/node_modules/assemble-utils/node_modules/session-cache/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by airtonix** [comment]
Yep, no idea what this is and I don't plan to fix it : 

1. nunjucks isn't suitable for patternlab, swig is far better
2. the filters and so forth are probably causing duplicate operations.

I plan to rewrite this with a focus on dealing with those two points.
